package com.calorietracker.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * JPA Entity representing an AI-generated meal plan for a user.
 * 
 * <p>Each user can have one meal plan at a time, generated by the Google Gemini AI
 * based on their profile, goals, and recent meal/weight history. The plan provides
 * a personalized 7-day meal schedule.</p>
 * 
 * <h2>Attributes:</h2>
 * <ul>
 *   <li><b>text:</b> The AI-generated meal plan content (stored as TEXT for large content)</li>
 *   <li><b>user:</b> One-to-one relationship with the plan owner</li>
 *   <li><b>createdAt/updatedAt:</b> Timestamps for tracking plan freshness</li>
 * </ul>
 * 
 * <h2>AI Integration:</h2>
 * <p>Plans are generated via {@link com.calorietracker.service.PlanService} which
 * calls the Gemini API with user context including meal history and weight trends.</p>
 * 
 * @author Calorie Tracker Team
 * @version 1.0.0
 * @see User
 * @see com.calorietracker.service.PlanService
 */
@Entity
@Table(name = "plans")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Plan {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(columnDefinition = "TEXT")
    private String text;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, unique = true)
    private User user;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
