package com.calorietracker.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * JPA Entity representing an AI-generated progress review for a user.
 * 
 * <p>Each user can have one progress review at a time, generated by the Google Gemini AI.
 * The review analyzes the user's adherence to their meal plan, calorie intake patterns,
 * and weight progress, providing actionable recommendations.</p>
 * 
 * <h2>Attributes:</h2>
 * <ul>
 *   <li><b>text:</b> The AI-generated review content (stored as TEXT for large content)</li>
 *   <li><b>user:</b> One-to-one relationship with the review owner</li>
 *   <li><b>createdAt/updatedAt:</b> Timestamps for tracking review freshness</li>
 * </ul>
 * 
 * <h2>AI Integration:</h2>
 * <p>Reviews are generated via {@link com.calorietracker.service.ReviewService} which
 * analyzes meal history, weight trends, and plan adherence to provide personalized feedback.</p>
 * 
 * @author Calorie Tracker Team
 * @version 1.0.0
 * @see User
 * @see com.calorietracker.service.ReviewService
 */
@Entity
@Table(name = "reviews")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Review {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(columnDefinition = "TEXT")
    private String text;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, unique = true)
    private User user;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
